all :   dp.cpp
	g++ dp.cpp

test2000: 
	  ./a.out < test2000.txt
test3000: 
	./a.out < test3000.txt
test5000: 
	./a.out < test5000.txt
test10000: 
	./a.out < test10000.txt
test30000: 
	./a.out < test30000.txt
test50000: 
	./a.out < test50000.txt
